### PR TITLE
JS file that adds weather call and pulls data for tomorrow's weather

### PR DESCRIPTION
**Pull request by isaacfallon**
Note: HTML text content needs to be linked. At this stage it just logs the relevant weather information to the console.

### CODE REVIEW

**Review by ZACGIL — COMMENTED** [review]
Really good, keep it up

**Review by SoniiPP — COMMENTED** [review]
Looks Great to go with

**Review by isaacfallon — COMMENTED** [review]
Added JS file for OpenWeather API call

**Review by ZACGIL — COMMENTED** [review]
Looks good

**Review by ZACGIL — APPROVED** [review]
Approved

**Pull request merged**
